package com.palmjoys.yf1b.act.majiang.model;

import com.palmjoys.yf1b.act.framework.annotation.SocketDefine;
import com.palmjoys.yf1b.act.framework.annotation.SocketModule;

@SocketDefine(value = "麻将游戏逻辑模块")
public interface MajiangDefine {
	@SocketModule("麻将游戏逻辑模块")
	int MAJIANGGAME = 5;
	
	static final int MAJIANGGAME_COMMAND_BASE = MAJIANGGAME*100;
	static final int MAJIANGGAME_ERROR_BASE = (0-MAJIANGGAME)*1000;
	static final int MAJIANGGAME_COMMAND_BASE_NOTIFY = MAJIANGGAME*10000;
	
	//command id
	//获取麻将条目规则配置
	int MAJIANGGAME_COMMAND_RULECFG = MAJIANGGAME_COMMAND_BASE + 1;
	//创建桌子
	int MAJIANGGAME_COMMAND_ROOM_CREATE = MAJIANGGAME_COMMAND_BASE + 2;
	//加入桌子
	int MAJIANGGAME_COMMAND_ROOM_JOIN = MAJIANGGAME_COMMAND_BASE + 3;
	//退出桌子
	int MAJIANGGAME_COMMAND_ROOM_LEAV = MAJIANGGAME_COMMAND_BASE + 4;
	//请求指定桌子信息
	int MAJIANGGAME_COMMAND_ROOM_INFO = MAJIANGGAME_COMMAND_BASE + 5;
	//换牌表态
	int MAJIANGGAME_COMMAND_SWAP_CARD = MAJIANGGAME_COMMAND_BASE + 6;
	//定缺表态
	int MAJIANGGAME_COMMAND_DINQUE = MAJIANGGAME_COMMAND_BASE + 7;
	//出牌表态
	int MAJIANGGAME_COMMAND_OUT_CARD = MAJIANGGAME_COMMAND_BASE + 8;
	//胡杠碰吃过表态
	int MAJIANGGAME_COMMAND_BREAK_CARD = MAJIANGGAME_COMMAND_BASE + 9;
	//申请解散桌子
	int MAJIANGGAME_COMMAND_TABLE_DESTORY_QUEST = MAJIANGGAME_COMMAND_BASE + 10;
	//解散桌子表态
	int MAJIANGGAME_COMMAND_TABLE_DESTORY_BT = MAJIANGGAME_COMMAND_BASE + 11;
	//点击进入下一局游戏
	int MAJIANGGAME_COMMAND_TABLE_NEXT_GAME = MAJIANGGAME_COMMAND_BASE + 12;
	//躺牌表态
	int MAJIANGGAME_COMMAND_TABLE_TANG_BT = MAJIANGGAME_COMMAND_BASE + 13;
	//报叫表态
	int MAJIANGGAME_COMMAND_TABLE_BAOJIAO_BT = MAJIANGGAME_COMMAND_BASE + 14;
	//乐山麻将胡碰杠表态状态
	int MAJIANGGAME_COMMAND_BREAK_CARD_LSMJ_BT = MAJIANGGAME_COMMAND_BASE + 15;
	//南充麻将漂牌表态
	int MAJIANGGAME_COMMAND_TABLE_PIAOPAI_BT = MAJIANGGAME_COMMAND_BASE + 16;
	//获取桌子密码标识
	int MAJIANGGAME_COMMAND_TABLE_PASSWORD_STATE = MAJIANGGAME_COMMAND_BASE + 17;
	//托管
	int MAJIANGGAME_COMMAND_TABLE_TRUSTEESHIP = MAJIANGGAME_COMMAND_BASE + 18;
	
	//推送消息(游戏状态变化)
	int MAJIANGGAME_COMMAND_TABLE_STATE_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 1;
	//推送消息(座位数据变化)
	int MAJIANGGAME_COMMAND_TABLE_SEAT_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 2;
	//推送消息(定缺数据通知)
	int MAJIANGGAME_COMMAND_DINQUE_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 3;
	//推送消息(换牌数据通知)
	int MAJIANGGAME_COMMAND_SWAPCARD_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 4;
	//推送消息(出牌数据通知)
	int MAJIANGGAME_COMMAND_OUTCARD_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 5;
	//推送消息(胡杠碰吃通知)
	int MAJIANGGAME_COMMAND_BREAKCARD_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 6;
	//推送消息(桌子已解散通知)
	int MAJIANGGAME_COMMAND_TABLE_DESTORY_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 7;
	//推送消息(桌子解散表态通知)
	int MAJIANGGAME_COMMAND_TABLE_DESTORY_BT_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 8;
	//推送消息(座位报叫表态通知)
	int MAJIANGGAME_COMMAND_TABLE_BAOJIAO_BT_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 9;
	//推送消息(南充麻将漂牌数据通知)
	int MAJIANGGAME_COMMAND_TABLE_PIAOPAI_BT_NOTIFY = MAJIANGGAME_COMMAND_BASE_NOTIFY + 10;
}
